fixing release config

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -25,8 +25,14 @@ jobs:
           go install github.com/dmarkham/enumer@latest
           echo "$HOME/go/bin" >> $GITHUB_PATH
           ls -la $HOME/go/bin
-          export PATH='$PATH:$HOME/go/bin'
+          export PATH=$PATH:$HOME/go/bin
           echo "Current PATH: $PATH"
+          if [ -x "enumer" ]; then
+            echo "Enumer installed successfully."
+          else
+            echo "Enumer installation failed."
+            exit 1
+          end
 
       - name: Generate code
         run: |
